version: '3.7'

services:
  db:
    image: mysql:5.7.21
    ports:
      - "3306"
    restart: always
    environment:
      MYSQL_DATABASE: testcont
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  app:
    image: javazg_tc:0.0.1
#    ports:
#      - "8081:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testcont?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_FLYWAY_URL: jdbc:mysql://db:3306/testcont?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_FLYWAY_USER: test
      SPRING_FLYWAY_PASSWORD: test
    networks:
      - backend


volumes:
  db-data:

networks:
  backend: